-- =====================================================================
-- Central CP — esquema de banco de dados (Supabase / Postgres)
-- =====================================================================
-- Este arquivo único virou histórico — o schema real agora está
-- organizado por tema em supabase/migrations/, numerados na ordem em
-- que precisam ser aplicados (dependência: extensões → tipos → tabelas
-- → RLS → webhook → storage). Ver README.md, seção "Como colocar para
-- rodar", pro passo a passo.
--
-- supabase/migrations/
--   0001_extensoes.sql                       — pgcrypto, pg_trgm
--   0002_tipos.sql                           — enums (user_role, nota_status, etc.)
--   0003_usuarios_delegacoes.sql             — usuarios, delegacoes, papeis/delegação
--   0004_cadastros.sql                       — pagadores, centros de custo, classes, códigos, fornecedores
--   0005_notas.sql                           — notas, rateios, histórico + índices
--   0006_rls_habilitar.sql                   — liga RLS em todas as tabelas
--   0007_rls_usuarios_delegacoes_cadastros.sql
--   0008_rls_notas.sql                       — policies de notas + trigger anti-cancelamento de paga
--   0009_rls_rateios_historico.sql           — policies de rateio/histórico + validação de soma
--   0010_webhook_notificacao.sql             — pg_net + e-mail a cada movimentação
--   0011_storage_anexos.sql                 — bucket e policies de anexos
--
-- Nenhuma regra de negócio mudou nessa reorganização — é só estrutura
-- (conferido linha a linha contra a versão anterior deste arquivo).
-- =====================================================================
